[project]
name = "RAG-against-the-machine"
version = "0.1.0"
description = "A retrieval-augmented generation (RAG) project designed to answer questions about a repository or documentation corpus"
readme = "README.md"
requires-python = ">=3.12.13" # The dataset we got is using some tricks that just allowed for >= 3.12
dependencies = [
	"bm25>=0.3.9",
	"faiss-cpu>=1.15.0",
	"fastapi[standard]>=0.141.1",
	"fire>=0.7.1",
	"flake8>=7.3.0",
	"langchain-text-splitters>=1.1.2",
	"pydantic>=2.13.4",
	"scikit-learn>=1.9.0",
	"sentence-transformers>=5.6.1",
	"torch>=2.13.0",
	"tqdm>=4.68.4",
	"transformers>=5.14.1",
]

# Let mypy Recognaize pydantic dataclasses
[tool.mypy]
plugins = ["pydantic.mypy"]

[tool.ruff]
line-length = 79

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true
docstring-code-line-length = 79
