[project]
name = "RAG-against-the-machine"
version = "0.1.0"
description = "RAG system"  # TODO: Update later.
readme = "README.md"
requires-python = ">=3.12.13" # The dataset we got is using some tricks that just allowed for >= 3.12
dependencies = [
    "langchain-text-splitters>=1.1.2",
    #"langchain>=1.3.11",
    "tiktoken>=0.13.0",
]
