[project]
name = "RAG-against-the-machine"
version = "0.1.0"
description = "RAG system"  # TODO: Update later.
readme = "README.md"
requires-python = ">=3.12.13" # The dataset we got is using some tricks that just allowed for >= 3.12
dependencies = [
    "fire>=0.7.1",
    "scikit-learn>=1.9.0",
    "tiktoken>=0.13.0",
    "tqdm>=4.68.4",
]
